%YAML 1.2
---

imports:
  - resource: secret_parameters.yml


app:
  sid: istex-exchange
  doProfile: false
  parallel: 5 # nb of reviewData that are processed in parallel
istex:
  api:
    url: %env(ISTEX_EXCHANGE_API_URL)%
    # timeout may be Object or Number, @see https://www.npmjs.com/package/got#timeout
    timeout: 10000 # ms
  review:
    url: %env(ISTEX_EXCHANGE_REVIEW_URL)%
    # timeout may be Object or Number, @see https://www.npmjs.com/package/got#timeout
    timeout:
     response: 5000 #ms

nodejs:
  stackTraceLimit: 40
