%YAML 1.2
---

parameters:
  ISTEX_EXCHANGE_USE_CACHE_LOOKUP: true
  ISTEX_EXCHANGE_API_URL: https://api.istex.fr
  ISTEX_EXCHANGE_REVIEW_URL: https://revue-sommaire.data.istex.fr

app:
  sid: istex-exchange
  doWarn: false
  doLogError: false
  doFrameByPublicationDate: false
  parallel: 15 # nb of reviewData that are processed in parallel, Warning: diminishing returns due to istex.api bottleneck.

testSuit:
  expectedAvgTimeByIteration: 300 # ms
  minTimeout: 5000 # ms

istex:
  api:
    url: %env(ISTEX_EXCHANGE_API_URL)%

    # Boolean This should stay disabled when making requests to internal hostnames, @see https://www.npmjs.com/package/got#dnscache
    useCacheLookup: %env(ISTEX_EXCHANGE_USE_CACHE_LOOKUP)%

    # timeout may be Object or Number, @see https://www.npmjs.com/package/got#timeout
    timeout:
     response: 10000 # ms

  review:
    url: %env(ISTEX_EXCHANGE_REVIEW_URL)%
    # timeout may be Object or Number, @see https://www.npmjs.com/package/got#timeout
    timeout:
     response: 5000 # ms

xmlHoldings:
  spaces: 0 # Number of spaces to be used for indenting XML output. Passing characters like ' ' or '\t' are also accepted.
  dtd: https://scholar.google.com/scholar/institutional_holdings.dtd
  maxXmlHoldingsSize: 1MB # limit of the file size by holdings, @see https://github.com/istex/istex-google-scholar/blob/master/resources/reference/institutional_holdings.xml
  # Supported units : b, kb, mb, gb, tb, pb
  outputPath: ./output/google-scholar

xmlLinks:
  dtd: https://scholar.google.com/scholar/institutional_links.dtd
  baseUrl: https://google-scholar.delivery.istex.fr

nodejs:
  stackTraceLimit: 40
