'use strict';

module.exports = {
  model: {
    _id: '_id',
    uri: 'uri',
    _query: '_query',
    lodexPublished: 'lodex_published',
    type: 'WmzM',
    title: 'XXRn',
    contributor: 'Ai4O',
    corpus: 'aCG7',
    issn: 'nC6e',
    eIssn: 'auA7',
    isbn: 'hLNF',
    eIsbn: 'YDZ9',
    istexQuery: 'BZSn',
    startDate: 'Rijz',
    endDate: 'ZLPq',
    publisher: 'UVFW',
    titleId: 'V7IG',
    precededBy: 'izmJ',
    followedBy: 'FdsN',
    creationDate: 'BblN',
    isPartOf: 'kber',
    rights: 'Fr7z',
    parentPublicationTitleId: 'XX3r',

  },
  duckTyping: [
    '_id',
    'uri',
    'type',
    'title',
  ],
  SERIAL: 'serial',
  MONOGRAPH: 'monograph',
  issnShape: 'nnnn-nnnn',
  syndicationFromModel: '/api/run/syndication-from/nC6e',
  corpusType: {
    elsevier: 'journals',
    wiley: 'journals',
    'springer-journals': 'journals',
    oup: 'journals',
    'springer-ebooks': 'ebooks',
    cambridge: 'journals',
    acs: 'journals',
    sage: 'journals',
    bmj: 'journals',
    iop: 'journals',
    nature: 'journals',
    'rsc-journals': 'journals',
    'degruyter-journals': 'journals',
    ecco: 'ebooks',
    'edp-sciences': 'journals',
    emerald: 'journals',
    'brill-journals': 'journals',
    eebo: 'ebooks',
    rsl: 'journals',
    'brepols-journals': 'journals',
    'rsc-ebooks': 'ebooks',
    'open-edition-ebooks': 'ebooks',
    droz: 'ebooks',
    lavoisier: 'journals',
    'brepols-ebooks': 'ebooks',
    'brill-hacco': 'ebooks',
    gsl: 'ebooks',
    duke: 'journals',
    'taylor-francis': 'ebooks',
    'numerique-premium': 'ebooks',

  },
};
